#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# TODO: Install oh-my-zsh shell

rm -rf $HOME/.zshrc
ln -s $DOTFILES/home/zshrc $HOME/.zshrc

rm -rf $HOME/.aerospace.toml
ln -s $DOTFILES/home/aerospace.toml $HOME/.aerospace.toml

rm -rf $HOME/.gitconfig
ln -s $DOTFILES/home/gitconfig $HOME/.gitconfig

rm -rf $HOME/.gitignore
ln -s $DOTFILES/home/gitignore $HOME/.gitignore

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin
rm -rf $HOME/.local/bin/t
ln -s $DOTFILES/scripts/t $HOME/.local/bin/t

mkdir -p $HOME/.config/nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

mkdir -p $HOME/.config/gitui
rm -rf $HOME/.config/gitui
ln -s $DOTFILES/gitui $HOME/.config/gitui

mkdir -p $HOME/.config/wezterm
rm -rf $HOME/.config/wezterm
ln -s $DOTFILES/wezterm $HOME/.config/wezterm
