# zmodload zsh/zprof

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# History settings.
HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

setopt INC_APPEND_HISTORY # Immediately append to history file:
setopt EXTENDED_HISTORY # Record timestamp in history:
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history:
setopt HIST_IGNORE_DUPS # Dont record an entry that was just recorded again:
setopt HIST_IGNORE_ALL_DUPS # Delete old recorded entry if new entry is a duplicate:
setopt HIST_FIND_NO_DUPS # Do not display a line previously found:
setopt HIST_IGNORE_SPACE # Dont record an entry starting with a space:
setopt HIST_SAVE_NO_DUPS # Dont write duplicate entries in the history file:
setopt SHARE_HISTORY # Share history between all sessions:

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY

export LANG=en_US.UTF-8

alias vim="nvim"
alias lg="gitui"
alias search="rg -i -uuu --no-ignore"
alias nvm="fnm"
alias uuid='uuidgen | tr "[:upper:]" "[:lower:]"'
alias claer="clear"

kube() {
  export KUBECONFIG="$HOME/Code/kube/personal.yml"
  echo "KUBECONFIG set to: $KUBECONFIG"
}

kubeuxd() {
  export KUBECONFIG="$HOME/Code/kube/uxd.yml"
  echo "KUBECONFIG set to: $KUBECONFIG"
}

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"

source ~/.secrets

# We are on macOS...
if [[ $(uname) == "Darwin" ]]; then
  alias kubectl-uxd="kubectl --kubeconfig=$HOME/Code/kube/uxd.yaml --insecure-skip-tls-verify"
  alias k9s="k9s --kubeconfig ~/Code/kube/personal.yml"
  alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'
  alias phpcsfixer='for file in $(git diff --name-only HEAD | grep "\.php$"); do PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix "$file"; done'
  alias phprec='vendor/bin/rector process $(git diff --name-only HEAD | paste -sd " " -)'
  alias phpfix='phpcsfixer && phprec'

  export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
  export PATH="/opt/homebrew/opt/ruby/bin:/usr/local/lib/ruby/gems/3.1.0/bin:$PATH"
  # export PATH="${HOME}/.pyenv/shims:${PATH}"

# We are on Linux...
elif command -v apt > /dev/null; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Unknown OS...
else
  echo 'Unknown OS!'
fi

# FNM (fast node manager)
eval "$(fnm env --use-on-cd)"

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
export PATH="/opt/homebrew/opt/bison/bin:$PATH"
