# zmodload zsh/zprof

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git autojump)

source $ZSH/oh-my-zsh.sh

# History settings.
HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

setopt INC_APPEND_HISTORY # Immediately append to history file:
setopt EXTENDED_HISTORY # Record timestamp in history:
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history:
setopt HIST_IGNORE_DUPS # Dont record an entry that was just recorded again:
setopt HIST_IGNORE_ALL_DUPS # Delete old recorded entry if new entry is a duplicate:
setopt HIST_FIND_NO_DUPS # Do not display a line previously found:
setopt HIST_IGNORE_SPACE # Dont record an entry starting with a space:
setopt HIST_SAVE_NO_DUPS # Dont write duplicate entries in the history file:
setopt SHARE_HISTORY # Share history between all sessions:

# Execute commands using history (e.g.: using !$) immediatel:
unsetopt HIST_VERIFY

export LANG=en_US.UTF-8

alias vim="nvim"
alias lg="gitui"
alias search="rg -uuu"
alias nvm="fnm"
alias uuid='uuidgen | tr "[:upper:]" "[:lower:]"'
alias claer="clear"

kube() {
  export KUBECONFIG="$HOME/Code/kube/personal.yml"
  echo "KUBECONFIG set to: $KUBECONFIG"
}

kubeuxd() {
  export KUBECONFIG="$HOME/Code/kube/uxd.yml"
  echo "KUBECONFIG set to: $KUBECONFIG"
}

# We are on macOS...
if [[ $(uname) == "Darwin" ]]; then
	source ~/.secrets

	alias kubectl-uxd="kubectl --kubeconfig=/Users/vblinden/Code/kube/uxd.yaml --insecure-skip-tls-verify"
	alias sail='sh $([ -f sail ] && echo sail || echo vendor/bin/sail)'
	alias phpcsfixer='for file in $(git diff --name-only HEAD | grep "\.php$"); do vendor/bin/php-cs-fixer fix "$file"; done'
	alias phprec='vendor/bin/rector process $(git diff --name-only HEAD | paste -sd " " -)'
	alias phpfix='phpcsfixer && phprec'

	export PATH="$HOME/.local/bin":$PATH
	export PATH="$HOME/.composer/vendor/bin:$PATH"
	export PATH="/Users/vblinden/go/bin:$PATH"
	export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"

	export PATH="/opt/homebrew/opt/ruby/bin:/usr/local/lib/ruby/gems/3.1.0/bin:$PATH"

# We are on Linux...
elif command -v apt > /dev/null; then
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# Unknown OS...
else
    echo 'Unknown OS!'
fi

# FNM (fast node manager)
eval "$(fnm env --use-on-cd)"

# FZF
eval "$(fzf --zsh)"

# -- Use fd instead of fzf --
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type=d --hidden --strip-cwd-prefix --exclude .git"

# Use fd (https://github.com/sharkdp/fd) for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --exclude .git . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type=d --hidden --exclude .git . "$1"
}

# bun completions
[ -s "/Users/vblinden/.bun/_bun" ] && source "/Users/vblinden/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"


# Herd injected PHP binary.
export PATH="/Users/vblinden/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/vblinden/Library/Application Support/Herd/config/php/84/"


# Herd injected PHP 8.3 configuration.
export HERD_PHP_83_INI_SCAN_DIR="/Users/vblinden/Library/Application Support/Herd/config/php/83/"
